version: '3.4'

services:
  athenaeum:
    image: ${DOCKER_REGISTRY-}athenaeum
    build:
      context: .
      dockerfile: Athenaeum/Dockerfile
  database:
    container_name: Athenaeum_DB_Cont
    build:
      context: .
      dockerfile: Database/Dockerfile
    environment:
      SA_PASSWORD: "101MyPass101"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"